### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by etiennemlb** [KhronosGroup/OpenCL-Registry#126]
Hi,
On the OpenCL spec registry (https://registry.khronos.org/OpenCL/) I beleive the OpenCL 2.0 C Language [Specification ](https://registry.khronos.org/OpenCL/specs/opencl-2.0-openclc.pdf)(April 13, 2016) link is dead.

**Comment by alycm** [comment]
Hello,

Thank you for your report.  Indeed the link is dead.  The target file was removed in PR https://github.com/KhronosGroup/OpenCL-Registry/pull/61 but it looks like this link was missed.

It was removed because the OpenCL C 2.0 specification was still getting revisions via OpenCL 2.1 and 2.2 (it was still OpenCL C 2.0, there was no OpenCL C 2.1 or 2.2).  The original OpenCL C 2.0 PDF did not have the fixes from the revisions and due to changing the source format of the specification it was not easy to maintain parallel versions.

Options to fix:

1. Link to the OpenCL C specification shipped for OpenCL 2.2, this is still describing OpenCL C 2.0.
2. Restore the previous OpenCL C 2.0 PDF, this is less attractive because it would be missing bug fixes from newer revisions.

**Comment by bashbaug** [comment]
I think we should "link" to the OpenCL C specification shipped for OpenCL 2.2.  I think this is better than restoring an older specification that is missing bug fixes, as Alastair mentioned.  I don't have a strong opinion whether we do this via a .htaccess file or just update the webpage itself - we'll probably want to update the modification date on the webpage regardless, so maybe that's the path of least resistance?
